### ISSUE TITLE
Feature: Add Support for Outlander PHEV Water Header (Can controlled Version)

### ISSUE THREAD

**Issue by jamiejones85** [damienmaguire/Stm32-vcu#61]
Details here https://openinverter.org/wiki/Mitsubishi_Outlander_Water_Heater

**Comment by jamiejones85** [comment]
https://github.com/jamiejones85/Stm32-vcu/tree/OutlanderHeater Will do a PR once tested in a working vehicle.

**Comment by riazarbi** [comment]
Howdy. I am motivated to test this out to get it merged to main. 

I have - 

1. a zombieverter
2. an outlander heater
3. a 12v water pump
4. pipes
5. wires


Any guidance as to what would constitute a valid test, @jamiejones85 ?

**Comment by Tom-evnut** [comment]
@jamiejones85 Once you are happy you can heat water with the latest release please close.

**Comment by jamiejones85** [comment]
Using it on my car at the moment.
